### login
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "stefanbesovic@gmail.com",
  "password": "bass"
}

> {%
 client.global.set("accessToken", response.headers.valueOf("Authorization").substring("Bearer ".length));
 %}

### list all users
GET http://localhost:8080/api/user
Accept: application/json
Authorization: Bearer {{accessToken}}

### add new user
POST http://localhost:8080/api/user
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
  "username": "mirko",
  "email": "mirko@gmail.com",
  "password": "mirko"
}

> {%
 client.global.set("objectId", response.body.id);
 %}

### get newly added user
GET http://localhost:8080/api/user/{{objectId}}
Accept: application/json
Authorization: Bearer {{accessToken}}

### update newly added user
PUT http://localhost:8080/api/user/{{objectId}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
  "username": "mirkomikic",
  "email": "mirko123@gmail.com",
  "password": "mirko123"
}

### delete newly added user
DELETE http://localhost:8080/api/user/{{objectId}}
Authorization: Bearer {{accessToken}}
