### login
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "stefanbesovic@gmail.com",
  "password": "bass"
}

> {%
 client.global.set("accessToken", response.headers.valueOf("Authorization").substring("Bearer ".length));
 %}

### list all votes
GET http://localhost:8080/api/vote
Accept: application/json
Authorization: Bearer {{accessToken}}

### save vote
POST http://localhost:8080/api/vote
Content-Type: multipart/form-data; boundary=boundary
Accept: application/json
Authorization: Bearer {{accessToken}}

--boundary
Content-Disposition: form-data; name="icon"; filename="angry.png"

< ../icons/angry.png

--boundary
Content-Disposition: form-data; name="request";
Content-Type: application/json

{
  "value": 5,
  "comment": "This is comment",
  "characterId": 2
}

> {%
 client.global.set("objectId", response.body.id);
 %}

### update created vote
PUT http://localhost:8080/api/vote/{{objectId}}
Content-Type: multipart/form-data; boundary=boundary
Accept: application/json
Authorization: Bearer {{accessToken}}

--boundary
Content-Disposition: form-data; name="icon"; filename=""


--boundary
Content-Disposition: form-data; name="request";
Content-Type: application/json

{
  "value": 10,
  "comment": "This is a new comment about this character",
  "characterId": 9
}

### list all votes
GET http://localhost:8080/api/vote
Accept: application/json
Authorization: Bearer {{accessToken}}

### delete created vote
DELETE http://localhost:8080/api/vote/{{objectId}}
Authorization: Bearer {{accessToken}}